import ImageProcessing as ip
import matplotlib.pyplot as pyplot
image = pyplot.imread("cat.png")
gray_image = ip.rgb_to_gray(image)
negative_image = ip.negative(image)
log_transform = ip.log_transformation(image)
figure = pyplot.figure()
figure.add_subplot(1, 4, 1)
pyplot.text(10,1500,"M Havid Albar P")
pyplot.title("Original")
pyplot.imshow(image, cmap=pyplot.get_cmap('gray'))
figure.add_subplot(1, 4, 2)
pyplot.title("Grayscale")
pyplot.imshow(gray_image, cmap=pyplot.get_cmap('gray'))
figure.add_subplot(1, 4, 3)
pyplot.title("Negative")
pyplot.imshow(negative_image)
figure.add_subplot(1,4,4)
pyplot.title("Log Transformation")
pyplot.imshow(log_transform, cmap = pyplot.get_cmap('gray'))
pyplot.show()
